package com.zklx.dao;

import com.zklx.domain.Aa;
import com.zklx.domain.AaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface AaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AA
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    long countByExample(AaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AA
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    int deleteByExample(AaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AA
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    int insert(Aa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AA
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    int insertSelective(Aa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AA
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    List<Aa> selectByExample(AaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AA
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") Aa record, @Param("example") AaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AA
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    int updateByExample(@Param("record") Aa record, @Param("example") AaExample example);
    
    @Select("select * from aa")
    List<Aa> selectAll();
}