package com.zklx.dao;

import com.zklx.domain.ComShort;
import com.zklx.domain.ComShortExample;
import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ComShortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    long countByExample(ComShortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int deleteByExample(ComShortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int insert(ComShort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int insertSelective(ComShort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    List<ComShort> selectByExampleWithBLOBs(ComShortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    List<ComShort> selectByExample(ComShortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    ComShort selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") ComShort record, @Param("example") ComShortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ComShort record, @Param("example") ComShortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int updateByExample(@Param("record") ComShort record, @Param("example") ComShortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int updateByPrimaryKeySelective(ComShort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COM_SHORT
     *
     * @mbg.generated Wed Aug 01 09:32:02 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ComShort record);
    
    
    @Select("select * from com_short where rownum<=1")
    public ComShort selectAll();
    
    @Delete("delete from com_short where rownum>=1")
    public int deleteAll();
    
    @Select("select count(*) from com_short ")
    int selectCountShort();
}