package com.zklx.dao;

import com.zklx.domain.Headbanner;
import com.zklx.domain.HeadbannerExample;
import com.zklx.domain.Product;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface HeadbannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    long countByExample(HeadbannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int deleteByExample(HeadbannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int deleteByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int insert(Headbanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int insertSelective(Headbanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    List<Headbanner> selectByExampleWithBLOBs(HeadbannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    List<Headbanner> selectByExample(HeadbannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    Headbanner selectByPrimaryKey(String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") Headbanner record, @Param("example") HeadbannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Headbanner record, @Param("example") HeadbannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int updateByExample(@Param("record") Headbanner record, @Param("example") HeadbannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int updateByPrimaryKeySelective(Headbanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Headbanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HEADBANNER
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    int updateByPrimaryKey(Headbanner record);
    

    /*@Select("select hid,title,website,photo,isshow,change_time,create_time from headbanner")*/
    List<Headbanner> selectAll();
    
    @Select("select count(*) from headbanner")
    int selecCountHB();
    
    
    int updateIsShowByID(Headbanner record);
}