package com.zklx.dao;

import com.zklx.domain.Logo;
import com.zklx.domain.LogoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface LogoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    long countByExample(LogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int deleteByExample(LogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int insert(Logo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int insertSelective(Logo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    List<Logo> selectByExampleWithBLOBs(LogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    List<Logo> selectByExample(LogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    Logo selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int updateByExampleSelective(@Param("record") Logo record, @Param("example") LogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Logo record, @Param("example") LogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int updateByExample(@Param("record") Logo record, @Param("example") LogoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int updateByPrimaryKeySelective(Logo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Logo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    int updateByPrimaryKey(Logo record);
    

    @Select("select * from logo")
    Logo selectAll();
    
    @Select("select count(*) from logo")
    int selectCountLogo();
    
}