package com.zklx.dao;

import com.zklx.domain.MappingRp;
import com.zklx.domain.MappingRpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MappingRpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    long countByExample(MappingRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int deleteByExample(MappingRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int deleteByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int insert(MappingRp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int insertSelective(MappingRp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    List<MappingRp> selectByExample(MappingRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    MappingRp selectByPrimaryKey(Long roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") MappingRp record, @Param("example") MappingRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByExample(@Param("record") MappingRp record, @Param("example") MappingRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByPrimaryKeySelective(MappingRp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MAPPING_RP
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByPrimaryKey(MappingRp record);
}