package com.zklx.dao;

import com.zklx.domain.ProApp;
import com.zklx.domain.ProAppExample;
import com.zklx.domain.ProIt;
import com.zklx.domain.ProMulti;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProAppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    long countByExample(ProAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int deleteByExample(ProAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int insert(ProApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int insertSelective(ProApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    List<ProApp> selectByExampleWithBLOBs(ProAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    List<ProApp> selectByExample(ProAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    ProApp selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProApp record, @Param("example") ProAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProApp record, @Param("example") ProAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByExample(@Param("record") ProApp record, @Param("example") ProAppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByPrimaryKeySelective(ProApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProApp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_APP
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByPrimaryKey(ProApp record);
    

    List<ProApp> selectAll();
    

    List<ProApp> selectBytitle(@Param("title") String title);
    

    @Select("select count(*) from pro_app")
    int selectCountApp();
}