package com.zklx.dao;

import com.zklx.domain.ProductDetail;
import com.zklx.domain.ProductDetailExample;
import com.zklx.domain.ProductDetailWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    long countByExample(ProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int deleteByExample(ProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int deleteByPrimaryKey(String did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int insert(ProductDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int insertSelective(ProductDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    List<ProductDetailWithBLOBs> selectByExampleWithBLOBs(ProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    List<ProductDetail> selectByExample(ProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    ProductDetailWithBLOBs selectByPrimaryKey(String did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductDetailWithBLOBs record, @Param("example") ProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProductDetailWithBLOBs record, @Param("example") ProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int updateByExample(@Param("record") ProductDetail record, @Param("example") ProductDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int updateByPrimaryKeySelective(ProductDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProductDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_DETAIL
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    int updateByPrimaryKey(ProductDetail record);
    
    ProductDetailWithBLOBs selectByBelong(String id);
}