package com.zklx.dao;

import com.zklx.domain.ProductSubChara;
import com.zklx.domain.ProductSubCharaExample;
import com.zklx.domain.ProductSubCharaWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSubCharaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    long countByExample(ProductSubCharaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int deleteByExample(ProductSubCharaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int insert(ProductSubCharaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int insertSelective(ProductSubCharaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    List<ProductSubCharaWithBLOBs> selectByExampleWithBLOBs(ProductSubCharaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    List<ProductSubChara> selectByExample(ProductSubCharaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    ProductSubCharaWithBLOBs selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductSubCharaWithBLOBs record, @Param("example") ProductSubCharaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProductSubCharaWithBLOBs record, @Param("example") ProductSubCharaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int updateByExample(@Param("record") ProductSubChara record, @Param("example") ProductSubCharaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int updateByPrimaryKeySelective(ProductSubCharaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProductSubCharaWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_CHARA
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    int updateByPrimaryKey(ProductSubChara record);

    ProductSubCharaWithBLOBs selectByBelong(String id);
    
    
    int countCh(String id);
}