package com.zklx.dao;

import com.zklx.domain.ProductSub;
import com.zklx.domain.ProductSubExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProductSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    long countByExample(ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int deleteByExample(ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int insert(ProductSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int insertSelective(ProductSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    List<ProductSub> selectByExample(ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    ProductSub selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductSub record, @Param("example") ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int updateByExample(@Param("record") ProductSub record, @Param("example") ProductSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int updateByPrimaryKeySelective(ProductSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB
     *
     * @mbg.generated Fri Jul 27 16:32:40 CST 2018
     */
    int updateByPrimaryKey(ProductSub record);
    
    List<ProductSub> selectAllInfoById(String id); 
    
    ProductSub selectFirstSub(String id);

    ProductSub selectSub(String id); 
    
    
    @Select("select count(*) from product_sub")
    int selectCountPro();
}