package com.zklx.dao;

import com.zklx.domain.ProductSubFunc;
import com.zklx.domain.ProductSubFuncExample;
import com.zklx.domain.ProductSubFuncWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSubFuncMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    long countByExample(ProductSubFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int deleteByExample(ProductSubFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int deleteByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int insert(ProductSubFuncWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int insertSelective(ProductSubFuncWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    List<ProductSubFuncWithBLOBs> selectByExampleWithBLOBs(ProductSubFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    List<ProductSubFunc> selectByExample(ProductSubFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    ProductSubFuncWithBLOBs selectByPrimaryKey(String pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProductSubFuncWithBLOBs record, @Param("example") ProductSubFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProductSubFuncWithBLOBs record, @Param("example") ProductSubFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int updateByExample(@Param("record") ProductSubFunc record, @Param("example") ProductSubFuncExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int updateByPrimaryKeySelective(ProductSubFuncWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProductSubFuncWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_SUB_FUNC
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    int updateByPrimaryKey(ProductSubFunc record);
    

    ProductSubFuncWithBLOBs selectByBelong(String id);
    
    int countFu(String id);
}