package com.zklx.dao;

import com.zklx.domain.ProIt;
import com.zklx.domain.ProItExample;
import com.zklx.domain.ProMulti;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProItMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    long countByExample(ProItExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int deleteByExample(ProItExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int insert(ProIt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int insertSelective(ProIt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    List<ProIt> selectByExampleWithBLOBs(ProItExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    List<ProIt> selectByExample(ProItExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    ProIt selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProIt record, @Param("example") ProItExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProIt record, @Param("example") ProItExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByExample(@Param("record") ProIt record, @Param("example") ProItExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByPrimaryKeySelective(ProIt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProIt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_IT
     *
     * @mbg.generated Mon Jul 23 11:24:36 CST 2018
     */
    int updateByPrimaryKey(ProIt record);
    

    List<ProIt> selectAll();

    List<ProIt> selectBytitle(@Param("title") String title);
   

    @Select(" select count(*) from pro_it")
    int selectCountIt();
}