package com.zklx.dao;

import com.zklx.domain.ProIt;
import com.zklx.domain.ProMulti;
import com.zklx.domain.ProMultiExample;
import com.zklx.domain.ProSystemHead;
import com.zklx.domain.ProSystemHeadWithBLOBs;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProMultiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    long countByExample(ProMultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int deleteByExample(ProMultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int deleteByPrimaryKey(String mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int insert(ProMulti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int insertSelective(ProMulti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    List<ProMulti> selectByExampleWithBLOBs(ProMultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    List<ProMulti> selectByExample(ProMultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    ProMulti selectByPrimaryKey(String mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProMulti record, @Param("example") ProMultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProMulti record, @Param("example") ProMultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int updateByExample(@Param("record") ProMulti record, @Param("example") ProMultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int updateByPrimaryKeySelective(ProMulti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProMulti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_MULTI
     *
     * @mbg.generated Mon Jul 23 11:01:19 CST 2018
     */
    int updateByPrimaryKey(ProMulti record);
    
    List<ProMulti> selectAll();

    List<ProMulti> selectBytitle(@Param("title") String title);
    

    @Select("select count(*) from pro_multi")
    int selectCountMul();
}