package com.zklx.dao;

import com.zklx.domain.ProSystemHead;
import com.zklx.domain.ProSystemHeadExample;
import com.zklx.domain.ProSystemHeadWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ProSystemHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    long countByExample(ProSystemHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int deleteByExample(ProSystemHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int insert(ProSystemHeadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int insertSelective(ProSystemHeadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    List<ProSystemHeadWithBLOBs> selectByExampleWithBLOBs(ProSystemHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    List<ProSystemHead> selectByExample(ProSystemHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    ProSystemHeadWithBLOBs selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") ProSystemHeadWithBLOBs record, @Param("example") ProSystemHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ProSystemHeadWithBLOBs record, @Param("example") ProSystemHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int updateByExample(@Param("record") ProSystemHead record, @Param("example") ProSystemHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int updateByPrimaryKeySelective(ProSystemHeadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ProSystemHeadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRO_SYSTEM_HEAD
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    int updateByPrimaryKey(ProSystemHead record);
    
    List<ProSystemHeadWithBLOBs> selectAll();

    List<ProSystemHeadWithBLOBs> selectByTitle(@Param("title")String title);
    
    @Select("select count(*) from pro_system_head")
    int selectCountCase();
    
    
}