package com.zklx.dao;

import com.zklx.domain.Rrole;
import com.zklx.domain.RroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    long countByExample(RroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int deleteByExample(RroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int insert(Rrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int insertSelective(Rrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    List<Rrole> selectByExample(RroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    Rrole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Rrole record, @Param("example") RroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByExample(@Param("record") Rrole record, @Param("example") RroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByPrimaryKeySelective(Rrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RROLE
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByPrimaryKey(Rrole record);
    
    List<Rrole> getRoles();

	void addRole(Rrole role);

	void deleterole(int roleid);// 删除一个角色

	void addRolePermission(int roleid, int permissionid);

	void deleterole_permission(int roleid, int permissionid);// 删除一个角色和一个权限的关联

	void deleteroles(int roleid);// 删除一个角色的所有权限关联

	Rrole getRolebyid(int roleid);

	void updateRole(Rrole role);
}