package com.zklx.dao;

import com.zklx.domain.Solution;
import com.zklx.domain.SolutionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SolutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    long countByExample(SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int deleteByExample(SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int insert(Solution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int insertSelective(Solution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    List<Solution> selectByExampleWithBLOBs(SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    List<Solution> selectByExample(SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    Solution selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Solution record, @Param("example") SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Solution record, @Param("example") SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int updateByExample(@Param("record") Solution record, @Param("example") SolutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int updateByPrimaryKeySelective(Solution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Solution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOLUTION
     *
     * @mbg.generated Wed Aug 08 16:29:07 CST 2018
     */
    int updateByPrimaryKey(Solution record);
    
    List<Solution> selectAll();
    

    @Select("select count(*) from Solution")
    int selecCountSolu();
}