package com.zklx.dao;

import com.zklx.domain.Succeful;
import com.zklx.domain.SuccefulExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SuccefulMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    long countByExample(SuccefulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int deleteByExample(SuccefulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int insert(Succeful record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int insertSelective(Succeful record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    List<Succeful> selectByExampleWithBLOBs(SuccefulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    List<Succeful> selectByExample(SuccefulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    Succeful selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") Succeful record, @Param("example") SuccefulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Succeful record, @Param("example") SuccefulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int updateByExample(@Param("record") Succeful record, @Param("example") SuccefulExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int updateByPrimaryKeySelective(Succeful record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Succeful record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUCCEFUL
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    int updateByPrimaryKey(Succeful record);
    
    List<Succeful> selectAll();
    

    @Select("select count(*) from succeful")
    int selecCountSucc();
}