package com.zklx.dao;

import com.zklx.domain.Uuser;
import com.zklx.domain.UuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    long countByExample(UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int deleteByExample(UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int insert(Uuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int insertSelective(Uuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    List<Uuser> selectByExample(UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    Uuser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Uuser record, @Param("example") UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByExample(@Param("record") Uuser record, @Param("example") UuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByPrimaryKeySelective(Uuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UUSER
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    int updateByPrimaryKey(Uuser record);
    
    List<Uuser> getusers();

    Uuser getUserByid(int userid);

    Uuser getUserByusername(String username);

	void deleteuser(int userid);

	void deleteuserrole(int userid, int roleid);

	void adduserrole(int userid, int roleid);

	void adduser(Uuser user);

	void updateuser(Uuser user);

	void deleteuseroles(int userid);
	Uuser findFirst();
}