package com.zklx.domain;

public class Aa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AA.A
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AA.B
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    private String b;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AA.A
     *
     * @return the value of AA.A
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AA.A
     *
     * @param a the value for AA.A
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AA.B
     *
     * @return the value of AA.B
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AA.B
     *
     * @param b the value for AA.B
     *
     * @mbg.generated Wed Aug 08 17:57:54 CST 2018
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }
}