package com.zklx.domain;

public class About {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.AID
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.COMNAME
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String comname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.TEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.ADDRESS
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.EMIAL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String emial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.COMTEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String comtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.PERSON1
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String person1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.PHONE
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.PERSON2
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String person2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.SERVICETEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private String servicetel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ABOUT.MAP
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    private byte[] map;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.AID
     *
     * @return the value of ABOUT.AID
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.AID
     *
     * @param aid the value for ABOUT.AID
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setAid(String aid) {
        this.aid = aid == null ? null : aid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.COMNAME
     *
     * @return the value of ABOUT.COMNAME
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getComname() {
        return comname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.COMNAME
     *
     * @param comname the value for ABOUT.COMNAME
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setComname(String comname) {
        this.comname = comname == null ? null : comname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.TEL
     *
     * @return the value of ABOUT.TEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.TEL
     *
     * @param tel the value for ABOUT.TEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.ADDRESS
     *
     * @return the value of ABOUT.ADDRESS
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.ADDRESS
     *
     * @param address the value for ABOUT.ADDRESS
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.EMIAL
     *
     * @return the value of ABOUT.EMIAL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getEmial() {
        return emial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.EMIAL
     *
     * @param emial the value for ABOUT.EMIAL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setEmial(String emial) {
        this.emial = emial == null ? null : emial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.COMTEL
     *
     * @return the value of ABOUT.COMTEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getComtel() {
        return comtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.COMTEL
     *
     * @param comtel the value for ABOUT.COMTEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setComtel(String comtel) {
        this.comtel = comtel == null ? null : comtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.PERSON1
     *
     * @return the value of ABOUT.PERSON1
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getPerson1() {
        return person1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.PERSON1
     *
     * @param person1 the value for ABOUT.PERSON1
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setPerson1(String person1) {
        this.person1 = person1 == null ? null : person1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.PHONE
     *
     * @return the value of ABOUT.PHONE
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.PHONE
     *
     * @param phone the value for ABOUT.PHONE
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.PERSON2
     *
     * @return the value of ABOUT.PERSON2
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getPerson2() {
        return person2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.PERSON2
     *
     * @param person2 the value for ABOUT.PERSON2
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setPerson2(String person2) {
        this.person2 = person2 == null ? null : person2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.SERVICETEL
     *
     * @return the value of ABOUT.SERVICETEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getServicetel() {
        return servicetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.SERVICETEL
     *
     * @param servicetel the value for ABOUT.SERVICETEL
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setServicetel(String servicetel) {
        this.servicetel = servicetel == null ? null : servicetel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ABOUT.MAP
     *
     * @return the value of ABOUT.MAP
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public byte[] getMap() {
        return map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ABOUT.MAP
     *
     * @param map the value for ABOUT.MAP
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setMap(byte[] map) {
        this.map = map;
    }
}