package com.zklx.domain;

import java.util.ArrayList;
import java.util.List;

public class AboutExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public AboutExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAidIsNull() {
            addCriterion("AID is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("AID is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(String value) {
            addCriterion("AID =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(String value) {
            addCriterion("AID <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(String value) {
            addCriterion("AID >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(String value) {
            addCriterion("AID >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(String value) {
            addCriterion("AID <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(String value) {
            addCriterion("AID <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLike(String value) {
            addCriterion("AID like", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotLike(String value) {
            addCriterion("AID not like", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<String> values) {
            addCriterion("AID in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<String> values) {
            addCriterion("AID not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(String value1, String value2) {
            addCriterion("AID between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(String value1, String value2) {
            addCriterion("AID not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andComnameIsNull() {
            addCriterion("COMNAME is null");
            return (Criteria) this;
        }

        public Criteria andComnameIsNotNull() {
            addCriterion("COMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andComnameEqualTo(String value) {
            addCriterion("COMNAME =", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotEqualTo(String value) {
            addCriterion("COMNAME <>", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameGreaterThan(String value) {
            addCriterion("COMNAME >", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameGreaterThanOrEqualTo(String value) {
            addCriterion("COMNAME >=", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameLessThan(String value) {
            addCriterion("COMNAME <", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameLessThanOrEqualTo(String value) {
            addCriterion("COMNAME <=", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameLike(String value) {
            addCriterion("COMNAME like", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotLike(String value) {
            addCriterion("COMNAME not like", value, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameIn(List<String> values) {
            addCriterion("COMNAME in", values, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotIn(List<String> values) {
            addCriterion("COMNAME not in", values, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameBetween(String value1, String value2) {
            addCriterion("COMNAME between", value1, value2, "comname");
            return (Criteria) this;
        }

        public Criteria andComnameNotBetween(String value1, String value2) {
            addCriterion("COMNAME not between", value1, value2, "comname");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andEmialIsNull() {
            addCriterion("EMIAL is null");
            return (Criteria) this;
        }

        public Criteria andEmialIsNotNull() {
            addCriterion("EMIAL is not null");
            return (Criteria) this;
        }

        public Criteria andEmialEqualTo(String value) {
            addCriterion("EMIAL =", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialNotEqualTo(String value) {
            addCriterion("EMIAL <>", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialGreaterThan(String value) {
            addCriterion("EMIAL >", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialGreaterThanOrEqualTo(String value) {
            addCriterion("EMIAL >=", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialLessThan(String value) {
            addCriterion("EMIAL <", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialLessThanOrEqualTo(String value) {
            addCriterion("EMIAL <=", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialLike(String value) {
            addCriterion("EMIAL like", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialNotLike(String value) {
            addCriterion("EMIAL not like", value, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialIn(List<String> values) {
            addCriterion("EMIAL in", values, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialNotIn(List<String> values) {
            addCriterion("EMIAL not in", values, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialBetween(String value1, String value2) {
            addCriterion("EMIAL between", value1, value2, "emial");
            return (Criteria) this;
        }

        public Criteria andEmialNotBetween(String value1, String value2) {
            addCriterion("EMIAL not between", value1, value2, "emial");
            return (Criteria) this;
        }

        public Criteria andComtelIsNull() {
            addCriterion("COMTEL is null");
            return (Criteria) this;
        }

        public Criteria andComtelIsNotNull() {
            addCriterion("COMTEL is not null");
            return (Criteria) this;
        }

        public Criteria andComtelEqualTo(String value) {
            addCriterion("COMTEL =", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelNotEqualTo(String value) {
            addCriterion("COMTEL <>", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelGreaterThan(String value) {
            addCriterion("COMTEL >", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelGreaterThanOrEqualTo(String value) {
            addCriterion("COMTEL >=", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelLessThan(String value) {
            addCriterion("COMTEL <", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelLessThanOrEqualTo(String value) {
            addCriterion("COMTEL <=", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelLike(String value) {
            addCriterion("COMTEL like", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelNotLike(String value) {
            addCriterion("COMTEL not like", value, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelIn(List<String> values) {
            addCriterion("COMTEL in", values, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelNotIn(List<String> values) {
            addCriterion("COMTEL not in", values, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelBetween(String value1, String value2) {
            addCriterion("COMTEL between", value1, value2, "comtel");
            return (Criteria) this;
        }

        public Criteria andComtelNotBetween(String value1, String value2) {
            addCriterion("COMTEL not between", value1, value2, "comtel");
            return (Criteria) this;
        }

        public Criteria andPerson1IsNull() {
            addCriterion("PERSON1 is null");
            return (Criteria) this;
        }

        public Criteria andPerson1IsNotNull() {
            addCriterion("PERSON1 is not null");
            return (Criteria) this;
        }

        public Criteria andPerson1EqualTo(String value) {
            addCriterion("PERSON1 =", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1NotEqualTo(String value) {
            addCriterion("PERSON1 <>", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1GreaterThan(String value) {
            addCriterion("PERSON1 >", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1GreaterThanOrEqualTo(String value) {
            addCriterion("PERSON1 >=", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1LessThan(String value) {
            addCriterion("PERSON1 <", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1LessThanOrEqualTo(String value) {
            addCriterion("PERSON1 <=", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1Like(String value) {
            addCriterion("PERSON1 like", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1NotLike(String value) {
            addCriterion("PERSON1 not like", value, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1In(List<String> values) {
            addCriterion("PERSON1 in", values, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1NotIn(List<String> values) {
            addCriterion("PERSON1 not in", values, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1Between(String value1, String value2) {
            addCriterion("PERSON1 between", value1, value2, "person1");
            return (Criteria) this;
        }

        public Criteria andPerson1NotBetween(String value1, String value2) {
            addCriterion("PERSON1 not between", value1, value2, "person1");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPerson2IsNull() {
            addCriterion("PERSON2 is null");
            return (Criteria) this;
        }

        public Criteria andPerson2IsNotNull() {
            addCriterion("PERSON2 is not null");
            return (Criteria) this;
        }

        public Criteria andPerson2EqualTo(String value) {
            addCriterion("PERSON2 =", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2NotEqualTo(String value) {
            addCriterion("PERSON2 <>", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2GreaterThan(String value) {
            addCriterion("PERSON2 >", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2GreaterThanOrEqualTo(String value) {
            addCriterion("PERSON2 >=", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2LessThan(String value) {
            addCriterion("PERSON2 <", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2LessThanOrEqualTo(String value) {
            addCriterion("PERSON2 <=", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2Like(String value) {
            addCriterion("PERSON2 like", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2NotLike(String value) {
            addCriterion("PERSON2 not like", value, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2In(List<String> values) {
            addCriterion("PERSON2 in", values, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2NotIn(List<String> values) {
            addCriterion("PERSON2 not in", values, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2Between(String value1, String value2) {
            addCriterion("PERSON2 between", value1, value2, "person2");
            return (Criteria) this;
        }

        public Criteria andPerson2NotBetween(String value1, String value2) {
            addCriterion("PERSON2 not between", value1, value2, "person2");
            return (Criteria) this;
        }

        public Criteria andServicetelIsNull() {
            addCriterion("SERVICETEL is null");
            return (Criteria) this;
        }

        public Criteria andServicetelIsNotNull() {
            addCriterion("SERVICETEL is not null");
            return (Criteria) this;
        }

        public Criteria andServicetelEqualTo(String value) {
            addCriterion("SERVICETEL =", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelNotEqualTo(String value) {
            addCriterion("SERVICETEL <>", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelGreaterThan(String value) {
            addCriterion("SERVICETEL >", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelGreaterThanOrEqualTo(String value) {
            addCriterion("SERVICETEL >=", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelLessThan(String value) {
            addCriterion("SERVICETEL <", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelLessThanOrEqualTo(String value) {
            addCriterion("SERVICETEL <=", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelLike(String value) {
            addCriterion("SERVICETEL like", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelNotLike(String value) {
            addCriterion("SERVICETEL not like", value, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelIn(List<String> values) {
            addCriterion("SERVICETEL in", values, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelNotIn(List<String> values) {
            addCriterion("SERVICETEL not in", values, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelBetween(String value1, String value2) {
            addCriterion("SERVICETEL between", value1, value2, "servicetel");
            return (Criteria) this;
        }

        public Criteria andServicetelNotBetween(String value1, String value2) {
            addCriterion("SERVICETEL not between", value1, value2, "servicetel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ABOUT
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 01 16:03:54 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ABOUT
     *
     * @mbg.generated Wed Aug 01 16:03:54 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}