package com.zklx.domain;

import java.util.Date;

public class Elegant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELEGANT.EID
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    private String eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELEGANT.TITLE
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELEGANT.CHANGE_TIME
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    private Date changeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELEGANT.CREATE_TIME
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELEGANT.PHOTO
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELEGANT.EID
     *
     * @return the value of ELEGANT.EID
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELEGANT.EID
     *
     * @param eid the value for ELEGANT.EID
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELEGANT.TITLE
     *
     * @return the value of ELEGANT.TITLE
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELEGANT.TITLE
     *
     * @param title the value for ELEGANT.TITLE
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELEGANT.CHANGE_TIME
     *
     * @return the value of ELEGANT.CHANGE_TIME
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELEGANT.CHANGE_TIME
     *
     * @param changeTime the value for ELEGANT.CHANGE_TIME
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELEGANT.CREATE_TIME
     *
     * @return the value of ELEGANT.CREATE_TIME
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELEGANT.CREATE_TIME
     *
     * @param createTime the value for ELEGANT.CREATE_TIME
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELEGANT.PHOTO
     *
     * @return the value of ELEGANT.PHOTO
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELEGANT.PHOTO
     *
     * @param photo the value for ELEGANT.PHOTO
     *
     * @mbg.generated Tue Aug 07 11:18:48 CST 2018
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    
    private String isshow;

	/**
	 * @return the isshow
	 */
	public String getIsshow() {
		return isshow;
	}

	/**
	 * @param isshow the isshow to set
	 */
	public void setIsshow(String isshow) {
		this.isshow = isshow;
	}
}