package com.zklx.domain;

import java.util.Date;

public class Headbanner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEADBANNER.HID
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    private String hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEADBANNER.TITLE
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEADBANNER.WEBSITE
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEADBANNER.ISSHOW
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    private String isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEADBANNER.CHANGE_TIME
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    private Date changeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEADBANNER.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HEADBANNER.PHOTO
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEADBANNER.HID
     *
     * @return the value of HEADBANNER.HID
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public String getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEADBANNER.HID
     *
     * @param hid the value for HEADBANNER.HID
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public void setHid(String hid) {
        this.hid = hid == null ? null : hid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEADBANNER.TITLE
     *
     * @return the value of HEADBANNER.TITLE
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEADBANNER.TITLE
     *
     * @param title the value for HEADBANNER.TITLE
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEADBANNER.WEBSITE
     *
     * @return the value of HEADBANNER.WEBSITE
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEADBANNER.WEBSITE
     *
     * @param website the value for HEADBANNER.WEBSITE
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEADBANNER.ISSHOW
     *
     * @return the value of HEADBANNER.ISSHOW
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public String getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEADBANNER.ISSHOW
     *
     * @param isshow the value for HEADBANNER.ISSHOW
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public void setIsshow(String isshow) {
        this.isshow = isshow == null ? null : isshow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEADBANNER.CHANGE_TIME
     *
     * @return the value of HEADBANNER.CHANGE_TIME
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEADBANNER.CHANGE_TIME
     *
     * @param changeTime the value for HEADBANNER.CHANGE_TIME
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEADBANNER.CREATE_TIME
     *
     * @return the value of HEADBANNER.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEADBANNER.CREATE_TIME
     *
     * @param createTime the value for HEADBANNER.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HEADBANNER.PHOTO
     *
     * @return the value of HEADBANNER.PHOTO
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HEADBANNER.PHOTO
     *
     * @param photo the value for HEADBANNER.PHOTO
     *
     * @mbg.generated Wed Aug 08 08:43:29 CST 2018
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    
    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return "getChangeTime:"+getChangeTime()+"  getTitle"+getTitle();
    }
}