package com.zklx.domain;

import java.util.Date;

public class Honor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONOR.SID
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONOR.TITLE
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONOR.CREATE_TIME
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HONOR.PHOTO
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONOR.SID
     *
     * @return the value of HONOR.SID
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONOR.SID
     *
     * @param sid the value for HONOR.SID
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONOR.TITLE
     *
     * @return the value of HONOR.TITLE
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONOR.TITLE
     *
     * @param title the value for HONOR.TITLE
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONOR.CREATE_TIME
     *
     * @return the value of HONOR.CREATE_TIME
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONOR.CREATE_TIME
     *
     * @param createTime the value for HONOR.CREATE_TIME
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HONOR.PHOTO
     *
     * @return the value of HONOR.PHOTO
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HONOR.PHOTO
     *
     * @param photo the value for HONOR.PHOTO
     *
     * @mbg.generated Mon Jul 23 14:02:16 CST 2018
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    
    private Date changeTime;
    
    /**
	 * @return the changeTime
	 */
	public Date getChangeTime() {
		return changeTime;
	}

	/**
	 * @param changeTime the changeTime to set
	 */
	public void setChangeTime(Date changeTime) {
		this.changeTime = changeTime;
	}

	@Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return "sid"+getSid()+"  getTitle():"+getTitle()+" getPhoto()"+getPhoto()+"getCreateTime()"+getCreateTime();
    }
}