package com.zklx.domain;

import java.util.Date;

public class Logo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGO.LID
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    private String lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGO.CHANGE_TIME
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    private Date changeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGO.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGO.PHOTO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGO.LID
     *
     * @return the value of LOGO.LID
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public String getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGO.LID
     *
     * @param lid the value for LOGO.LID
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public void setLid(String lid) {
        this.lid = lid == null ? null : lid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGO.CHANGE_TIME
     *
     * @return the value of LOGO.CHANGE_TIME
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGO.CHANGE_TIME
     *
     * @param changeTime the value for LOGO.CHANGE_TIME
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGO.CREATE_TIME
     *
     * @return the value of LOGO.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGO.CREATE_TIME
     *
     * @param createTime the value for LOGO.CREATE_TIME
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGO.PHOTO
     *
     * @return the value of LOGO.PHOTO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGO.PHOTO
     *
     * @param photo the value for LOGO.PHOTO
     *
     * @mbg.generated Wed Aug 08 15:15:57 CST 2018
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}