package com.zklx.domain;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component()
@Scope("prototype")
public class MappingRp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAPPING_RP.ROLEID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MAPPING_RP.PERMISSIONID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private Long permissionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAPPING_RP.ROLEID
     *
     * @return the value of MAPPING_RP.ROLEID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAPPING_RP.ROLEID
     *
     * @param roleid the value for MAPPING_RP.ROLEID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MAPPING_RP.PERMISSIONID
     *
     * @return the value of MAPPING_RP.PERMISSIONID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public Long getPermissionid() {
        return permissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MAPPING_RP.PERMISSIONID
     *
     * @param permissionid the value for MAPPING_RP.PERMISSIONID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setPermissionid(Long permissionid) {
        this.permissionid = permissionid;
    }
    

	private Rrole role;

	private Permission permission;

	/**
	 * @return the role
	 */
	public Rrole getRole() {
		return role;
	}

	/**
	 * @param role the role to set
	 */
	public void setRole(Rrole role) {
		this.role = role;
	}

	/**
	 * @return the permission
	 */
	public Permission getPermission() {
		return permission;
	}

	/**
	 * @param permission the permission to set
	 */
	public void setPermission(Permission permission) {
		this.permission = permission;
	}
}