package com.zklx.domain;

import java.util.List;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;


@Component("permission")
@Scope("prototype")
public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.PNAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.ID
     *
     * @return the value of PERMISSION.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.ID
     *
     * @param id the value for PERMISSION.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.PNAME
     *
     * @return the value of PERMISSION.PNAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.PNAME
     *
     * @param pname the value for PERMISSION.PNAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }
    
	private List<MappingRp> mapping_RP;

	/**
	 * @return the mapping_RP
	 */
	public List<MappingRp> getMapping_RP() {
		return mapping_RP;
	}

	/**
	 * @param mapping_RP the mapping_RP to set
	 */
	public void setMapping_RP(List<MappingRp> mapping_RP) {
		this.mapping_RP = mapping_RP;
	}
}