package com.zklx.domain;

public class ProductDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.DID
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */ 
    private String did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.SHCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String shcontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.SHNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String shname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.CHCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String chcontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.CHNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String chname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.FUCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String fucontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.FUNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String funame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.FUENGNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String fuengname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.PACONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String pacontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.PANAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String paname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.BELONGID
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private String belongid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.DID
     *
     * @return the value of PRODUCT_DETAIL.DID
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.DID
     *
     * @param did the value for PRODUCT_DETAIL.DID
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setDid(String did) {
        this.did = did == null ? null : did.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.SHCONTEXT
     *
     * @return the value of PRODUCT_DETAIL.SHCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getShcontext() {
        return shcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.SHCONTEXT
     *
     * @param shcontext the value for PRODUCT_DETAIL.SHCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setShcontext(String shcontext) {
        this.shcontext = shcontext == null ? null : shcontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.SHNAME
     *
     * @return the value of PRODUCT_DETAIL.SHNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getShname() {
        return shname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.SHNAME
     *
     * @param shname the value for PRODUCT_DETAIL.SHNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setShname(String shname) {
        this.shname = shname == null ? null : shname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.CHCONTEXT
     *
     * @return the value of PRODUCT_DETAIL.CHCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getChcontext() {
        return chcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.CHCONTEXT
     *
     * @param chcontext the value for PRODUCT_DETAIL.CHCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setChcontext(String chcontext) {
        this.chcontext = chcontext == null ? null : chcontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.CHNAME
     *
     * @return the value of PRODUCT_DETAIL.CHNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getChname() {
        return chname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.CHNAME
     *
     * @param chname the value for PRODUCT_DETAIL.CHNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setChname(String chname) {
        this.chname = chname == null ? null : chname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.FUCONTEXT
     *
     * @return the value of PRODUCT_DETAIL.FUCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getFucontext() {
        return fucontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.FUCONTEXT
     *
     * @param fucontext the value for PRODUCT_DETAIL.FUCONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setFucontext(String fucontext) {
        this.fucontext = fucontext == null ? null : fucontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.FUNAME
     *
     * @return the value of PRODUCT_DETAIL.FUNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getFuname() {
        return funame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.FUNAME
     *
     * @param funame the value for PRODUCT_DETAIL.FUNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setFuname(String funame) {
        this.funame = funame == null ? null : funame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.FUENGNAME
     *
     * @return the value of PRODUCT_DETAIL.FUENGNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getFuengname() {
        return fuengname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.FUENGNAME
     *
     * @param fuengname the value for PRODUCT_DETAIL.FUENGNAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setFuengname(String fuengname) {
        this.fuengname = fuengname == null ? null : fuengname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.PACONTEXT
     *
     * @return the value of PRODUCT_DETAIL.PACONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getPacontext() {
        return pacontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.PACONTEXT
     *
     * @param pacontext the value for PRODUCT_DETAIL.PACONTEXT
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setPacontext(String pacontext) {
        this.pacontext = pacontext == null ? null : pacontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.PANAME
     *
     * @return the value of PRODUCT_DETAIL.PANAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getPaname() {
        return paname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.PANAME
     *
     * @param paname the value for PRODUCT_DETAIL.PANAME
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setPaname(String paname) {
        this.paname = paname == null ? null : paname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.BELONGID
     *
     * @return the value of PRODUCT_DETAIL.BELONGID
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public String getBelongid() {
        return belongid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.BELONGID
     *
     * @param belongid the value for PRODUCT_DETAIL.BELONGID
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setBelongid(String belongid) {
        this.belongid = belongid == null ? null : belongid.trim();
    }
}