package com.zklx.domain;

public class ProductSubFuncWithBLOBs extends ProductSubFunc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_FUNC.CONTEXT
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    private byte[] context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_FUNC.FPHOTO
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    private byte[] fphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_FUNC.CONTEXT
     *
     * @return the value of PRODUCT_SUB_FUNC.CONTEXT
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    public byte[] getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_FUNC.CONTEXT
     *
     * @param context the value for PRODUCT_SUB_FUNC.CONTEXT
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    public void setContext(byte[] context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_FUNC.FPHOTO
     *
     * @return the value of PRODUCT_SUB_FUNC.FPHOTO
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    public byte[] getFphoto() {
        return fphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_FUNC.FPHOTO
     *
     * @param fphoto the value for PRODUCT_SUB_FUNC.FPHOTO
     *
     * @mbg.generated Wed Aug 22 09:23:05 CST 2018
     */
    public void setFphoto(byte[] fphoto) {
        this.fphoto = fphoto;
    }
}