package com.zklx.domain;

public class ProductSubShortWithBLOBs extends ProductSubShort {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_SHORT.CONTEXT
     *
     * @mbg.generated Tue Aug 21 17:08:21 CST 2018
     */
    private byte[] context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_SHORT.SPHOTO
     *
     * @mbg.generated Tue Aug 21 17:08:21 CST 2018
     */
    private byte[] sphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_SHORT.CONTEXT
     *
     * @return the value of PRODUCT_SUB_SHORT.CONTEXT
     *
     * @mbg.generated Tue Aug 21 17:08:21 CST 2018
     */
    public byte[] getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_SHORT.CONTEXT
     *
     * @param context the value for PRODUCT_SUB_SHORT.CONTEXT
     *
     * @mbg.generated Tue Aug 21 17:08:21 CST 2018
     */
    public void setContext(byte[] context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_SHORT.SPHOTO
     *
     * @return the value of PRODUCT_SUB_SHORT.SPHOTO
     *
     * @mbg.generated Tue Aug 21 17:08:21 CST 2018
     */
    public byte[] getSphoto() {
        return sphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_SHORT.SPHOTO
     *
     * @param sphoto the value for PRODUCT_SUB_SHORT.SPHOTO
     *
     * @mbg.generated Tue Aug 21 17:08:21 CST 2018
     */
    public void setSphoto(byte[] sphoto) {
        this.sphoto = sphoto;
    }
    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return "getPid():"+getPid()+" getPname()"+getPname()+" getContext()"+getContext()+" getBelong"+getBelong();
    }
}