package com.zklx.domain;

public class ProductSubCharaWithBLOBs extends ProductSubChara {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_CHARA.CONTEXT
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    private byte[] context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_CHARA.CPHOTO
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    private byte[] cphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_CHARA.CONTEXT
     *
     * @return the value of PRODUCT_SUB_CHARA.CONTEXT
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    public byte[] getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_CHARA.CONTEXT
     *
     * @param context the value for PRODUCT_SUB_CHARA.CONTEXT
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    public void setContext(byte[] context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_CHARA.CPHOTO
     *
     * @return the value of PRODUCT_SUB_CHARA.CPHOTO
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    public byte[] getCphoto() {
        return cphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_CHARA.CPHOTO
     *
     * @param cphoto the value for PRODUCT_SUB_CHARA.CPHOTO
     *
     * @mbg.generated Wed Aug 22 09:07:08 CST 2018
     */
    public void setCphoto(byte[] cphoto) {
        this.cphoto = cphoto;
    }
}