package com.zklx.domain;

import java.util.List;

public class ProductSub {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB.PID
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB.PNAME
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB.BELONG
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    private String belong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB.PID
     *
     * @return the value of PRODUCT_SUB.PID
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB.PID
     *
     * @param pid the value for PRODUCT_SUB.PID
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB.PNAME
     *
     * @return the value of PRODUCT_SUB.PNAME
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB.PNAME
     *
     * @param pname the value for PRODUCT_SUB.PNAME
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB.BELONG
     *
     * @return the value of PRODUCT_SUB.BELONG
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB.BELONG
     *
     * @param belong the value for PRODUCT_SUB.BELONG
     *
     * @mbg.generated Fri Jul 27 15:59:26 CST 2018
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }
     
    
    private List<ProductDetailWithBLOBs> productDetailWithBLOBs;

	/**
	 * @return the productDetailWithBLOBs
	 */
	public List<ProductDetailWithBLOBs> getProductDetailWithBLOBs() {
		return productDetailWithBLOBs;
	}

	/**
	 * @param productDetailWithBLOBs the productDetailWithBLOBs to set
	 */
	public void setProductDetailWithBLOBs(List<ProductDetailWithBLOBs> productDetailWithBLOBs) {
		this.productDetailWithBLOBs = productDetailWithBLOBs;
	}
    
}