package com.zklx.domain;

public class ProductDetailWithBLOBs extends ProductDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.SHPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private byte[] shphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.CHPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private byte[] chphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.FUPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private byte[] fuphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_DETAIL.PAPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    private byte[] paphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.SHPHOTO
     *
     * @return the value of PRODUCT_DETAIL.SHPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public byte[] getShphoto() {
        return shphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.SHPHOTO
     *
     * @param shphoto the value for PRODUCT_DETAIL.SHPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setShphoto(byte[] shphoto) {
        this.shphoto = shphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.CHPHOTO
     *
     * @return the value of PRODUCT_DETAIL.CHPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public byte[] getChphoto() {
        return chphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.CHPHOTO
     *
     * @param chphoto the value for PRODUCT_DETAIL.CHPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setChphoto(byte[] chphoto) {
        this.chphoto = chphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.FUPHOTO
     *
     * @return the value of PRODUCT_DETAIL.FUPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public byte[] getFuphoto() {
        return fuphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.FUPHOTO
     *
     * @param fuphoto the value for PRODUCT_DETAIL.FUPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setFuphoto(byte[] fuphoto) {
        this.fuphoto = fuphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_DETAIL.PAPHOTO
     *
     * @return the value of PRODUCT_DETAIL.PAPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public byte[] getPaphoto() {
        return paphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_DETAIL.PAPHOTO
     *
     * @param paphoto the value for PRODUCT_DETAIL.PAPHOTO
     *
     * @mbg.generated Mon Jul 30 09:20:13 CST 2018
     */
    public void setPaphoto(byte[] paphoto) {
        this.paphoto = paphoto;
    }
}