package com.zklx.domain;

public class ProductSubPara {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_PARA.PID
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_PARA.CONTEXT
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    private String context;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_PARA.BELONG
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    private String belong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_SUB_PARA.PNAME
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    private byte[] pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_PARA.PID
     *
     * @return the value of PRODUCT_SUB_PARA.PID
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_PARA.PID
     *
     * @param pid the value for PRODUCT_SUB_PARA.PID
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_PARA.CONTEXT
     *
     * @return the value of PRODUCT_SUB_PARA.CONTEXT
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_PARA.CONTEXT
     *
     * @param context the value for PRODUCT_SUB_PARA.CONTEXT
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_PARA.BELONG
     *
     * @return the value of PRODUCT_SUB_PARA.BELONG
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_PARA.BELONG
     *
     * @param belong the value for PRODUCT_SUB_PARA.BELONG
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_SUB_PARA.PNAME
     *
     * @return the value of PRODUCT_SUB_PARA.PNAME
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public byte[] getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_SUB_PARA.PNAME
     *
     * @param pname the value for PRODUCT_SUB_PARA.PNAME
     *
     * @mbg.generated Sat Jul 28 08:48:56 CST 2018
     */
    public void setPname(byte[] pname) {
        this.pname = pname;
    }
    @Override
    public String toString() {
    	// TODO Auto-generated method stub
    	return "getPid"+getPid()+" getPname"+getPname()+" getContext"+getContext()+" getBelong"+getBelong();
    }
}