package com.zklx.domain;

public class ProSystemHeadWithBLOBs extends ProSystemHead {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRO_SYSTEM_HEAD.INTRODUCITON
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    private byte[] introduciton;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRO_SYSTEM_HEAD.MYPHOTO
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    private byte[] myphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRO_SYSTEM_HEAD.INTRODUCITON
     *
     * @return the value of PRO_SYSTEM_HEAD.INTRODUCITON
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    public byte[] getIntroduciton() {
        return introduciton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRO_SYSTEM_HEAD.INTRODUCITON
     *
     * @param introduciton the value for PRO_SYSTEM_HEAD.INTRODUCITON
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    public void setIntroduciton(byte[] introduciton) {
        this.introduciton = introduciton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRO_SYSTEM_HEAD.MYPHOTO
     *
     * @return the value of PRO_SYSTEM_HEAD.MYPHOTO
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    public byte[] getMyphoto() {
        return myphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRO_SYSTEM_HEAD.MYPHOTO
     *
     * @param myphoto the value for PRO_SYSTEM_HEAD.MYPHOTO
     *
     * @mbg.generated Thu Jul 12 14:54:18 CST 2018
     */
    public void setMyphoto(byte[] myphoto) {
        this.myphoto = myphoto;
    }
    @Override
    public String toString() {
    	
    	return "sid:"+getSid()+" Title："+getTitle()+" getPname:"+getPname()+" getIntroduciton:"+getIntroduciton();
    }
}