package com.zklx.domain;

import java.util.List;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;


@Component("rrole")
@Scope("prototype")
public class Rrole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RROLE.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RROLE.NAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RROLE.ID
     *
     * @return the value of RROLE.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RROLE.ID
     *
     * @param id the value for RROLE.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RROLE.NAME
     *
     * @return the value of RROLE.NAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RROLE.NAME
     *
     * @param name the value for RROLE.NAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    
	private List<MappingUr> mapping_UR;

	private List<MappingRp> mapping_RP;

	/**
	 * @return the mapping_UR
	 */
	public List<MappingUr> getMapping_UR() {
		return mapping_UR;
	}

	/**
	 * @param mapping_UR the mapping_UR to set
	 */
	public void setMapping_UR(List<MappingUr> mapping_UR) {
		this.mapping_UR = mapping_UR;
	}

	/**
	 * @return the mapping_RP
	 */
	public List<MappingRp> getMapping_RP() {
		return mapping_RP;
	}

	/**
	 * @param mapping_RP the mapping_RP to set
	 */
	public void setMapping_RP(List<MappingRp> mapping_RP) {
		this.mapping_RP = mapping_RP;
	}
	
	@Override
	public String toString() {
		return "Role [roleid=" + id + ", name=" + name + ", mapping_UR=" + mapping_UR + ", mapping_RP=" + mapping_RP
				+ "]";
	}
}