package com.zklx.domain;

import java.util.Date;

public class Succeful {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUCCEFUL.SID
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUCCEFUL.TITLE
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUCCEFUL.CHANGE_TIME
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    private Date changeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUCCEFUL.CREATE_TIME
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUCCEFUL.SCONTENT
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    private byte[] scontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUCCEFUL.SID
     *
     * @return the value of SUCCEFUL.SID
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUCCEFUL.SID
     *
     * @param sid the value for SUCCEFUL.SID
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUCCEFUL.TITLE
     *
     * @return the value of SUCCEFUL.TITLE
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUCCEFUL.TITLE
     *
     * @param title the value for SUCCEFUL.TITLE
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUCCEFUL.CHANGE_TIME
     *
     * @return the value of SUCCEFUL.CHANGE_TIME
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUCCEFUL.CHANGE_TIME
     *
     * @param changeTime the value for SUCCEFUL.CHANGE_TIME
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUCCEFUL.CREATE_TIME
     *
     * @return the value of SUCCEFUL.CREATE_TIME
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUCCEFUL.CREATE_TIME
     *
     * @param createTime the value for SUCCEFUL.CREATE_TIME
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUCCEFUL.SCONTENT
     *
     * @return the value of SUCCEFUL.SCONTENT
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public byte[] getScontent() {
        return scontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUCCEFUL.SCONTENT
     *
     * @param scontent the value for SUCCEFUL.SCONTENT
     *
     * @mbg.generated Mon Aug 13 16:47:16 CST 2018
     */
    public void setScontent(byte[] scontent) {
        this.scontent = scontent;
    }
}