package com.zklx.domain;

import java.util.List;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;


@SuppressWarnings("serial")
@Component("uuser")
@Scope("prototype")
public class Uuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUSER.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUSER.USERNAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UUSER.PASSWORD
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUSER.ID
     *
     * @return the value of UUSER.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUSER.ID
     *
     * @param id the value for UUSER.ID
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUSER.USERNAME
     *
     * @return the value of UUSER.USERNAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUSER.USERNAME
     *
     * @param username the value for UUSER.USERNAME
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UUSER.PASSWORD
     *
     * @return the value of UUSER.PASSWORD
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UUSER.PASSWORD
     *
     * @param password the value for UUSER.PASSWORD
     *
     * @mbg.generated Fri Aug 10 09:46:56 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
    
	private List<MappingUr> mapping_UR;

	public List<MappingUr> getMapping_UR() {
		return mapping_UR;
	}

	public void setMapping_UR(List<MappingUr> mapping_UR) {
		this.mapping_UR = mapping_UR;
	}
	@Override
	public String toString() {
		return "User [userid=" + id + ", username=" + username + ", password=" + password + ", mapping_UR="
				+ mapping_UR + "]";
	}
	private String oldpass;

	/**
	 * @return the oldpass
	 */
	public String getOldpass() {
		return oldpass;
	}

	/**
	 * @param oldpass the oldpass to set
	 */
	public void setOldpass(String oldpass) {
		this.oldpass = oldpass;
	}
	
}