package com.zklx.domain;

public class ZkUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZK_USER.USERID
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZK_USER.USERNAME
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZK_USER.PASS
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    private String pass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZK_USER.USERID
     *
     * @return the value of ZK_USER.USERID
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZK_USER.USERID
     *
     * @param userid the value for ZK_USER.USERID
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZK_USER.USERNAME
     *
     * @return the value of ZK_USER.USERNAME
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZK_USER.USERNAME
     *
     * @param username the value for ZK_USER.USERNAME
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZK_USER.PASS
     *
     * @return the value of ZK_USER.PASS
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZK_USER.PASS
     *
     * @param pass the value for ZK_USER.PASS
     *
     * @mbg.generated Thu Jul 12 10:03:51 CST 2018
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }
}